<!-- BEGIN FOOTER -->

	<div class="footer">

		<div class="footer-inner">

			2014 &copy; Metronic by veecar.

		</div>

		<div class="footer-tools">

			<span class="go-top">

			<i class="icon-angle-up"></i>

			</span>

		</div>

	</div>

	<!-- END FOOTER -->

	<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->

	<!-- BEGIN CORE PLUGINS -->

	<script src="<?php  echo $this->basePath('media/js/jquery-1.10.1.min.js');?>" type="text/javascript"></script>

	<script src="<?php echo $this->basePath('media/js/jquery-migrate-1.2.1.min.js');?>" type="text/javascript"></script>

	<!-- IMPORTANT! Load jquery-ui-1.10.1.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->

	<script src="<?php echo $this->basePath('media/js/jquery-ui-1.10.1.custom.min.js');?>" type="text/javascript"></script>      

	<script src="<?php echo $this->basePath('media/js/bootstrap.min.js');?>" type="text/javascript"></script>

	<!--[if lt IE 9]>

	<script src="<?php echo $this->basePath('media/js/excanvas.min.js');?>"></script>

	<script src="<?php echo $this->basePath('media/js/respond.min.js');?>"></script>  

	<![endif]-->   

	<script src="<?php echo $this->basePath('media/js/jquery.slimscroll.min.js');?>" type="text/javascript"></script>

	<script src="<?php echo $this->basePath('media/js/jquery.blockui.min.js');?>" type="text/javascript"></script>  

	<script src="<?php echo $this->basePath('media/js/jquery.cookie.min.js');?>" type="text/javascript"></script>

	<script src="<?php echo $this->basePath('media/js/jquery.uniform.min.js');?>" type="text/javascript" ></script>

	<!-- END CORE PLUGINS -->

	<script src="<?php echo $this->basePath('media/js/app.js');?>"></script>      

	<script>

		jQuery(document).ready(function() {    

		   App.init();

		});

	</script>

	<!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>