
<!-- BEGIN FOOTER -->
<div class="page-footer">
	<div class="page-footer-inner">
		 2014 &copy; Metronic by keenthemes.
	</div>
	<div class="page-footer-tools">
		<span class="go-top">
		<i class="fa fa-angle-up"></i>
		</span>
	</div>
</div>
<!-- END FOOTER -->
<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->

<!--[if lt IE 9]>
<script src="<?php echo $this->basePath('assets');?>/global/plugins/respond.min.js"></script>
<script src="<?php echo $this->basePath('assets');?>/global/plugins/excanvas.min.js"></script> 
<![endif]-->
<script src="<?php echo $this->basePath('assets');?>/global/plugins/jquery-1.11.0.min.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets');?>/global/plugins/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
<!-- IMPORTANT! Load jquery-ui-1.10.3.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
<script src="<?php echo $this->basePath('assets');?>/global/plugins/jquery-ui/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets');?>/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets');?>/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets');?>/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets');?>/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets');?>/global/plugins/jquery.cokie.min.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets');?>/global/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets');?>/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<script src="<?php echo $this->basePath('assets');?>/global/scripts/metronic.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets');?>/admin/layout/scripts/layout.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets');?>/admin/layout/scripts/quick-sidebar.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets');?>/admin/layout/scripts/demo.js" type="text/javascript"></script> <!-- 切换主题演示 -->


<script>
jQuery(document).ready(function() {   
    // initiate layout and plugins
    Metronic.init(); // init metronic core components
    Layout.init(); // init current layout
    QuickSidebar.init(); // init quick sidebar
    Demo.init(); // init demo features <!-- 切换主题演示 -->
    
});
</script>
<!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>