<!-- BEGIN HEAD -->
<head>
<meta charset="utf-8"/>
<title><?php echo $page_title;?></title>
<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<meta content="" name="description"/>
<meta content="" name="author"/>
<!-- BEGIN GLOBAL MANDATORY STYLES -->
<!--
<link href="http://fonts.useso.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css"/>
-->
<link href="<?php echo $this->basePath('assets');?>/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->basePath('assets');?>/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->basePath('assets');?>/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->basePath('assets');?>/global/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->basePath('assets');?>/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css"/>
<!-- END GLOBAL MANDATORY STYLES -->


<!-- BEGIN THEME STYLES -->
<link href="<?php echo $this->basePath('assets');?>/global/css/components.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->basePath('assets');?>/global/css/plugins.css" rel="stylesheet" type="text/css"/><!-- 插件兼容css -->
<link href="<?php echo $this->basePath('assets');?>/admin/layout/css/layout.css" rel="stylesheet" type="text/css"/><!-- 框架布局 -->
<link href="<?php echo $this->basePath('assets');?>/admin/layout/css/themes/default.css" rel="stylesheet" type="text/css" id="style_color"/><!-- 默认主题 -->
<link href="<?php echo $this->basePath('assets');?>/admin/layout/css/custom.css" rel="stylesheet" type="text/css"/><!-- 圆角css -->
<!-- END THEME STYLES -->
<link rel="shortcut icon" href="favicon.ico"/>
<script>
var base_url='<?php echo  SITE_URL;?>';

function get_url(uri){
	return base_url+"/"+uri;
}
</script>
</head>
<!-- END HEAD -->
