<!DOCTYPE html>

<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->

<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->

<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->

<!-- BEGIN HEAD -->

<head>

	<meta charset="utf-8" />

	<title><?php echo $page_title ?></title>

	<meta content="width=device-width, initial-scale=1.0" name="viewport" />

	<meta content="" name="description" />

	<meta content="" name="author" />

	<!-- BEGIN GLOBAL MANDATORY STYLES -->
	<link href="<?php echo $this->basePath('media/css/bootstrap.min.css');?>" rel="stylesheet" type="text/css"/>

	<link href="<?php echo $this->basePath('media/css/bootstrap-responsive.min.css');?>" rel="stylesheet" type="text/css"/>

	<link href="<?php echo $this->basePath('media/css/font-awesome.min.css');?>" rel="stylesheet" type="text/css"/>

	<link href="<?php echo $this->basePath('media/css/style-metro.css');?>" rel="stylesheet" type="text/css"/>

	<link href="<?php echo $this->basePath('media/css/style.css');?>" rel="stylesheet" type="text/css"/>

	<link href="<?php echo $this->basePath('media/css/style-responsive.css');?>" rel="stylesheet" type="text/css"/>

	<link href="<?php echo $this->basePath('media/css/default.css');?>" rel="stylesheet" type="text/css" id="style_color"/>

	<link href="<?php echo $this->basePath('media/css/uniform.default.css');?>" rel="stylesheet" type="text/css"/>

	<!-- END GLOBAL MANDATORY STYLES -->

	<!-- BEGIN PAGE LEVEL STYLES -->

	<link href="<?php echo $this->basePath('media/css/error.css');?>" rel="stylesheet" type="text/css"/>

	<!-- END PAGE LEVEL STYLES -->

	<link rel="shortcut icon" href="<?php echo $this->basePath('media/image/favicon.ico');?>" />

</head>
<!-- END HEAD -->

<!-- BEGIN BODY -->

<body class="page-header-fixed">

	<!-- BEGIN HEADER -->