
<div class="page-sidebar nav-collapse collapse">

	<!-- BEGIN SIDEBAR MENU -->        

	<ul class="page-sidebar-menu">

		<li>
			<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
			<div class="sidebar-toggler hidden-phone"></div>
			<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
		</li>

		<li>
			<!-- BEGIN RESPONSIVE QUICK SEARCH FORM -->
			<form class="sidebar-search">
				<div class="input-box">
					<a href="javascript:;" class="remove"></a>
					<input type="text" placeholder="Search..." />
					<input type="button" class="submit" value=" " />
				</div>
			</form>
			<!-- END RESPONSIVE QUICK SEARCH FORM -->
		</li>
        
        
        <li class="start ">
			<a href="/">
			<i class="icon-home"></i> 
			<span class="title">HOME</span>
			</a>
		</li>


<?php 
function show_nav($arr,$way=false){
    $str = '';
    foreach($arr as $nav){
        $active=($way&&in_array($nav['id'],$way));
        if($active){
            $str.='<li class="active">';
        }else{
            $str.='<li>';
        }
        $str.='<a href="javascript:;">';
        if(!empty($nav['icon'])){
            $str.='<i class="icon-'.$nav['icon'].'"></i>';
        }
        if($nav['fid']==0){
            $str.='<span class="title">'.$nav['show_name'].'</span>';
            if($active) $str.='<span class="selected"></span>';
        }else{
            $str.=$nav['show_name'];
        }
        if(!empty($nav['children'])){
            if($active){
                $str.='<span class="arrow open"></span>';
            }else{
                $str.='<span class="arrow"></span>';
            }
        }
        $str.='</a>';
        if(!empty($nav['children'])){
            if($active){
                $str.='<ul class="sub-menu">';
            }else{
                $str.='<ul class="sub-menu" style="display:none;">';
            }
            $str.=show_nav($nav['children'],$way);
            $str.='</ul>';
        }
        $str.='</li>';
    }
    return $str;
};
echo show_nav($nav_arr,$way);
?>

        
	</ul>

	<!-- END SIDEBAR MENU -->

</div>