<!-- BEGIN SIDEBAR -->
	<div class="page-sidebar-wrapper">
		<!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
		<!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
		<div class="page-sidebar navbar-collapse collapse">
			<!-- BEGIN SIDEBAR MENU -->
			<ul class="page-sidebar-menu" data-auto-scroll="true" data-slide-speed="200">
				<!-- DOC: To remove the sidebar toggler from the sidebar you just need to completely remove the below "sidebar-toggler-wrapper" LI element -->
				<li class="sidebar-toggler-wrapper">
					<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
					<div class="sidebar-toggler">
					</div>
					<!-- END SIDEBAR TOGGLER BUTTON -->
				</li>
				<!-- DOC: To remove the search box from the sidebar you just need to completely remove the below "sidebar-search-wrapper" LI element -->
				<li class="sidebar-search-wrapper">
					<!-- BEGIN RESPONSIVE QUICK SEARCH FORM -->
					<!-- DOC: Apply "sidebar-search-bordered" class the below search form to have bordered search box -->
					<!-- DOC: Apply "sidebar-search-bordered sidebar-search-solid" class the below search form to have bordered & solid search box -->
					<form class="sidebar-search " action="extra_search.html" method="POST">
						<a href="javascript:;" class="remove">
						<i class="icon-close"></i>
						</a>
						<div class="input-group">
							<input type="text" class="form-control" placeholder="Search...">
							<span class="input-group-btn">
							<a href="javascript:;" class="btn submit"><i class="icon-magnifier"></i></a>
							</span>
						</div>
					</form>
					<!-- END RESPONSIVE QUICK SEARCH FORM -->
				</li>
                
                
				<li class="start">
					<a href="javascript:;">
					<i class="icon-home"></i>
					<span class="title">HOME</span>
					</a>
				</li>
                
<?php 
function show_nav($arr,$way=false){
    $str = '';
    foreach($arr as $nav){
        $active=($way&&in_array($nav['id'],$way));
        if($active){
            $str.='<li class="active">';
        }else{
            $str.='<li>';
        }
        $str.='<a href="javascript:;">';
        if(!empty($nav['icon'])){
            $str.='<i class="icon-'.$nav['icon'].'"></i>';
        }
        if($nav['fid']==0){
            $str.='<span class="title">'.$nav['show_name'].'</span>';
            if($active) $str.='<span class="selected"></span>';
        }else{
            $str.=$nav['show_name'];
        }
        if(!empty($nav['children'])){
            if($active){
                $str.='<span class="arrow open"></span>';
            }else{
                $str.='<span class="arrow"></span>';
            }
        }
        $str.='</a>';
        if(!empty($nav['children'])){
            if($active){
                $str.='<ul class="sub-menu">';
            }else{
                $str.='<ul class="sub-menu" style="display:none;">';
            }
            $str.=show_nav($nav['children'],$way);
            $str.='</ul>';
        }
        $str.='</li>';
    }
    return $str;
};
echo show_nav($nav_arr,$way);
?>                
                
				<li class="last">
					<a href="javascript:;">
					<i class="icon-pointer"></i>
					<span class="title">访问统计</span>
					</a>
				</li>
			</ul>
			<!-- END SIDEBAR MENU -->
		</div>
	</div>
	<!-- END SIDEBAR -->