<!DOCTYPE html>

<html lang="en" class="no-js">

<body>



<form method="post" action="<?php echo $this->url('rbac/index/addItem')?>">
name:<input name="name" >
type:<select name="type"><option value="0">操作<option><option value="1">任务<option><option value="2">角色<option></select>
<input type="submit" value="添加">
</form>

<table>
	<thead>
		<tr><th>名称</th><th>类型</th><th>操作</th></tr>
	</thead>
	<tbody>
	<?php foreach($itemlist['list'] as $item): ?>
		<tr><th><?php echo $item['name'] ?></th><th><?php echo $item['type'] ?></th><th>编辑</th></tr>
	<?php endforeach; ?>
	</tbody>
</table>

</body>

</html>